name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 7.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install FPM and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
      
      - name: Update version
        run: |
          # Update version in build.sh
          sed -i "s/VERSION=.*/VERSION=\"${{ github.event.inputs.version }}\"/" build.sh
          # Update version in config.py
          sed -i "s/APP_VERSION = .*/APP_VERSION = \"${{ github.event.inputs.version }}\"/" client/config.py
      
      - name: Build RPM package
        run: |
          chmod +x build.sh
          ./build.sh rpm
      
      - name: Build DEB package
        run: |
          ./build.sh deb
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.rpm
            dist/*.deb
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          generate_release_notes: true
          tag_name: v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 